version: '3.1'

services:
  rabbitmq:
    image: rabbitmq:management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
  mongodb:
    image: mongo:3.6.3
    restart: always
    ports:
      - "27017:27017"
    environment:
          MONGO_INITDB_ROOT_USERNAME: user
          MONGO_INITDB_ROOT_PASSWORD: pass
          MONGO_INITDB_DATABASE: test_db
  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
